---

- name: Set up a local isolated vm for colte development
  hosts: ['colte', 'colteBionic', 'colteFocal']
  become: yes

  tasks:
    - name: Install mongo key
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-4.2.asc"
        state: present

    - name: Install mongo repo
      apt_repository:
        repo: "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main"
        state: present
      when: ansible_distribution_release == "buster"

    - name: Install open5gs OBS key
      apt_key:
        url: "https://download.opensuse.org/repositories/home:/acetcom:/open5gs:/latest/Debian_10/Release.key"
        state: present
      when: ansible_distribution_release == "buster"

    - name: Install open5gs OBS repo
      apt_repository:
        repo: "deb http://download.opensuse.org/repositories/home:/acetcom:/open5gs:/latest/Debian_10/ ./"
        state: present
      when: ansible_distribution_release == "buster"

    - name: Install open5gs PPA
      apt_repository:
        repo: "ppa:open5gs/latest"
        state: present
      when: ansible_distribution_release == "bionic"

    - name: Install open5gs PPA
      apt_repository:
        repo: "ppa:open5gs/latest"
        state: present
      when: ansible_distribution_release == "focal"

    - name: Install colte key
      apt_key:
        url: "http://colte.cs.washington.edu/colte-archive-keyring.gpg"
        state: present

    - name: Install colte repo
      apt_repository:
        repo: "deb http://colte.cs.washington.edu {{ ansible_distribution_release }} main"
        state: present

    - name: Install utilities for terminal interaction
      apt:
        pkg: ['ccze', 'tmux', 'python3-dev', 'emacs-nox', 'usbutils']
        state: present
        update_cache: yes
        cache_valid_time: 600

    - name: Copy Tmux Config
      copy:
        src: "files/tmux.conf"
        dest: "/home/vagrant/.tmux.conf"
        remote_src: no
